
/* Milestone #3: quiz grading plus the same accessible mobile menu used site-wide. */
const menuButton=document.querySelector('.menu-toggle');const menu=document.querySelector('#primary-menu');
if(menuButton&&menu){menuButton.addEventListener('click',()=>{const isOpen=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(isOpen));});}
const quizForm=document.querySelector('#http-quiz');const resetButton=document.querySelector('#reset-quiz');const summary=document.querySelector('#quiz-summary');
function normalizeText(value){return value.trim().toLowerCase().replace(/\s+/g,' ')}
function sameAnswers(user,correct){return [...user].sort().join('|')===[...correct].sort().join('|')}
function showFeedback(number,isCorrect,userAnswer,correctAnswer){const card=document.querySelector(`#question-${number}`);const feedback=document.querySelector(`#feedback-q${number}`);card.classList.remove('correct-answer','incorrect-answer');card.classList.add(isCorrect?'correct-answer':'incorrect-answer');feedback.innerHTML=`<p class="feedback-status">${isCorrect?'✓ Correct — 1/1 point':'✗ Incorrect — 0/1 points'}</p><p><strong>Your answer:</strong> ${userAnswer||'No answer provided'}</p><p><strong>Correct answer:</strong> ${correctAnswer}</p>`;}
if(quizForm){quizForm.addEventListener('submit',event=>{event.preventDefault();let score=0;const q1=document.querySelector('#q1').value;const c1=['hypertext transfer protocol','hyper text transfer protocol'].includes(normalizeText(q1));score+=c1;showFeedback(1,c1,q1.trim(),'Hypertext Transfer Protocol');const answers={2:'HTTPS',3:'GET',4:'404'};for(const [n,correct] of Object.entries(answers)){const selected=document.querySelector(`input[name="q${n}"]:checked`);const value=selected?selected.value:'';const ok=value===correct;score+=ok;showFeedback(n,ok,value,correct)}const q5=[...document.querySelectorAll('input[name="q5"]:checked')].map(x=>x.value);const correct5=['GET','POST','PUT','DELETE'];const c5=sameAnswers(q5,correct5);score+=c5;showFeedback(5,c5,q5.join(', '),correct5.join(', '));const percent=Math.round(score/5*100);const passed=score>=4;summary.hidden=false;summary.className=`quiz-summary ${passed?'pass-summary':'fail-summary'}`;summary.innerHTML=`<h2>${passed?'PASS':'FAIL'}</h2><p><strong>Total score: ${score}/5 (${percent}%)</strong></p><p>${passed?'Great work! You demonstrated a strong understanding of the HTTP concepts covered on this site.':'Review the feedback, revisit the research pages, and try again.'}</p>`;summary.focus();});
resetButton.addEventListener('click',()=>{quizForm.reset();document.querySelectorAll('.question-card').forEach(x=>x.classList.remove('correct-answer','incorrect-answer'));document.querySelectorAll('.question-feedback').forEach(x=>x.innerHTML='');summary.hidden=true;summary.className='quiz-summary';summary.innerHTML='';document.querySelector('#q1').focus();});}
